version: "3.0"
services:
        ubuntu:
                build: .
                stdin_open: true # docker run -i
                tty: true        # docker run -t
                volumes:
                   - ../data:/home/duck/data
                   - ../scripts:/home/duck/scripts

        ubuntu-arm:
                build: ./arm
                stdin_open: true        # docker run -i
                tty: true               # docker run -t
                volumes:
                   - ../data:/home/duck/data
                   - ../scripts:/home/duck/scripts
